/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/

const app = require('./myApp.js');
const fs = require('fs');
const path = require('path');

// CORS
app.use(function (req, res, next) {
  res.set({
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, content-type, Accept',
  });
  next();
});

app.get('/file/*', function (req, res, next) {
  if (req.params[0] === '.env') {
    return next({ status: 401, message: 'ACCESS DENIED' });
  }
  fs.readFile(path.join(__dirname, req.params[0]), function (err, data) {
    if (err) return next(err);
    res.type('txt').send(data.toString());
  });
});

app.get('/app-info', function (req, res) {
  const appStack = app._router.stack
    .filter(s => s.name && !['query', 'expressInit', 'serveStatic', '<anonymous>'].includes(s.name))
    .map(s => s.name);

  const headers = res.getHeaders();
  const filtered = Object.fromEntries(
    Object.entries(headers).filter(([k]) => !k.startsWith('access-control-'))
  );

  res.json({ headers: filtered, appStack });
});

app.get('/package.json', function (req, res, next) {
  fs.readFile(__dirname + '/package.json', function (err, data) {
    if (err) return next(err);
    res.type('txt').send(data.toString());
  });
});

app.use(function (req, res) {
  res.status(404).type('txt').send('Not Found');
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Your app is listening on port ${port}`);
});

module.exports = app;