/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/

const main = require('./myApp.js');
const fs = require('fs');
const path = require('path');

// CORS
main.use(function (req, res, next) {
  res.set({
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, content-type, Accept',
  });
  next();
});

main.get('/file/*', function (req, res, next) {
  if (req.params[0] === '.env') {
    return next({ status: 401, message: 'ACCESS DENIED' });
  }
  fs.readFile(path.join(__dirname, req.params[0]), function (err, data) {
    if (err) return next(err);
    res.type('txt').send(data.toString());
  });
});

main.get('/_api/app-info', function (req, res) {
  var appMainRouteStack = main._router.stack
    .filter(s => s.path === '')
    .map(l => {
      if (l.name === 'xPoweredByMiddleware') return 'hidePoweredBy';
      return l.name;
    })
    .filter(n => !(n === 'query' || n === 'expressInit' || n === 'serveStatic'));

  var headers = res.getHeaders();
  var hObj = {};
  Object.keys(headers)
    .filter(h => !h.match(/^access-control-\w+/))
    .forEach(h => { hObj[h] = headers[h]; });

  res.json({ headers: hObj, appStack: appMainRouteStack });
});

main.get('/package.json', function (req, res, next) {
  fs.readFile(__dirname + '/package.json', function (err, data) {
    if (err) return next(err);
    res.type('txt').send(data.toString());
  });
});

main.use(function (req, res) {
  res.status(404).type('txt').send('Not Found');
});

const port = process.env.PORT || 3000;
main.listen(port, () => {
  console.log(`Your app is listening on port ${port}`);
});

module.exports = main;